baseURL = 'https://toolmeke.nz/'
languageCode = 'en-nz'
title = 'ToolMeke - Independent Tool Price Comparison'
theme = 'ananke'

[params]
  description = "Independent tool price comparison across New Zealand hardware stores - no affiliations, just helpful data"
  show_reading_time = false
  background_color_class = "bg-dark-gray"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Brands"
    url = "/brands/"
    weight = 20
  [[menu.main]]
    name = "Tools"
    url = "/tools/"
    weight = 30
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 40
